using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Pbk.Entities.Views
{
    [Keyless]
    public partial class GnlYuk_Deniz_v0VW
    {
        public long? isemrino { get; set; }
        public int yukno { get; set; }
        public int? firmano { get; set; }
        public string? FirmaAdi { get; set; }
        public int? gonderici { get; set; }
        public string? Gonderici_Adi { get; set; }
        public int? alici { get; set; }
        public string? Alici_Adi { get; set; }
        public int? ihbar { get; set; }
        public string? ihbar_Adi { get; set; }
        public int? ihbar2 { get; set; }
        public string? ihbar_Adi2 { get; set; }
        public int? banka2 { get; set; }
        public string? banka_Adi2 { get; set; }
        public int? imalatci { get; set; }
        public string? imalatci_Adi2 { get; set; }
        public string? denizarakonsimento { get; set; }
        public DateTime? arakonsimentotarih { get; set; }
        public string? dnCikisLiman { get; set; }
        public string? CikisLimanAdi { get; set; }
        public string? dnCikisYer { get; set; }
        public string? CikisYerAdi { get; set; }
        public string? dnVarisLiman { get; set; }
        public string? VarisLimanAdi { get; set; }
        public string? dnVarisYer { get; set; }
        public string? VarisYerAdi { get; set; }
        public string? dnYuklemeTipi { get; set; }
        public DateTime? dnETS { get; set; }
        public string? dnYuklemeYeri { get; set; }
        public string? dnrezervno { get; set; }
        public double? kap { get; set; }
        public string? birim { get; set; }
        public double? burutkg { get; set; }
        public double? netkg { get; set; }
        public double? cubic { get; set; }
        public double? lademetre { get; set; }
        public int? YuklemeHafta { get; set; }
        public DateTime? yuklentarih { get; set; }
        public string? YuklenUlkeAdi { get; set; }
        public string? yuklenulke { get; set; }
        public string? yukdepartman { get; set; }
        public string? karsilayandepartman { get; set; }
        public DateTime? cutoff { get; set; }
        public DateTime? istenenbitistartihi { get; set; }
        public string? bosalulke { get; set; }
        public string? BosalUlkeAdi { get; set; }
        public string? malturkadi { get; set; }
        public string? malingadi { get; set; }
        public string? gteslimsekli { get; set; }
        public string? departman { get; set; }
        public string? BglTrFileNo { get; set; }
        public int? dnAcenta { get; set; }
        public string? dnacenta_adi { get; set; }
        public int? dnGemiAcenta { get; set; }
        public string? dnGemiAcentaAdi { get; set; }
        public string? dnliner { get; set; }
        public string? dnLinerAd { get; set; }
        public string? dnGemiKodu { get; set; }
        public string? Gemi { get; set; }
        public string? dnGemiSeferNo { get; set; }
        public int sirket { get; set; }
        public int yil { get; set; }
        public int? insuser { get; set; }
        public string? insuserAdi { get; set; }
        public DateTime? instime { get; set; }
        public string? inshafta { get; set; }
        public int? upduser { get; set; }
        public DateTime? updtime { get; set; }
        public string? durum { get; set; }
        public string? DurumAdi { get; set; }
        public int? seferdeniz { get; set; }
        public int? seferhava { get; set; }
        public int? seferkara { get; set; }
        public string? yiimex { get; set; }
        public string? ydimex { get; set; }
        public string? nteslimsekli { get; set; }
        public string? NavlunOdemeYeri { get; set; }
        public string? Nominasyon { get; set; }
        public bool? naksekd { get; set; }
        public int? dosyadeniz { get; set; }
        public bool? EtiketBasilmayacak { get; set; }
        public string? yuktipi { get; set; }
        public bool? ictasima { get; set; }
        public bool? bosalicTasima { get; set; }
        public string? dnAnaKonsimentoNo { get; set; }
        public DateTime? dnAnaKonsimentoTarih { get; set; }
        public string? AktarmaAnaKonsimentoNo { get; set; }
        public DateTime? AktarmaAnaKonsimentoTarih { get; set; }
        public double? navlun { get; set; }
        public string? navlundovtur { get; set; }
        public bool? OzetBeyanGrup { get; set; }
        public string? dnKonteynerBilgi { get; set; }
        public DateTime? SeferCikisTarihi { get; set; }
        public DateTime? seferVarisTarihi { get; set; }
        public string? EdiTescilNo { get; set; }
        public DateTime? EdiTescilTarih { get; set; }
        public string? trArsivNo { get; set; }
        public string? AktarmaGemiKodu { get; set; }
        public string? AktarmaGemiAdi { get; set; }
        public string? AktarmaGemiSeferNo { get; set; }
        public string? OzelDurum { get; set; }
        public string? OzetBeyanGondericiAdi { get; set; }
        public string? OzetBeyanAliciAdi { get; set; }
        public string? EvrakAliciAdi { get; set; }
        public bool Arsiv { get; set; }
        public string? salesprice { get; set; }
        public string? firmaisno1 { get; set; }
        public string? firmaisno2 { get; set; }
        public string? firmaisno3 { get; set; }
        public string? firmaisno4 { get; set; }
        public int? customerShipper { get; set; }
        public int? customerConsignee { get; set; }
        public int? loadingAcenta { get; set; }
        public string? ExBglFileNo { get; set; }
        public string? ImBglFileNo { get; set; }
        public string? loadingacentaadi { get; set; }
        public string? vergino { get; set; }
        public string? Manufactureradi { get; set; }
        public bool? ydisibitmis { get; set; }
        public DateTime? ydisibitmisdate { get; set; }
        public string? dnacenta_Vergino { get; set; }
        public string? HBLtype { get; set; } = null!;
        public string? StatusPlace { get; set; }
        public DateTime? StatusDate { get; set; }
        public DateTime? dnATD { get; set; }
        public DateTime? dnATA { get; set; }
        public bool GumrukYapildi { get; set; }
        public bool MaddeGirisiYapildi { get; set; }
        public string? arakonsimento { get; set; }
        public DateTime? warehouseindate { get; set; }
        public double? malbedelidov { get; set; }
        public string? malbedelidovtur { get; set; }
        public string? USA_AltBolge { get; set; }
        public bool? notagency { get; set; }
        public string? specialshipment { get; set; }
        public short? exyuksira { get; set; }
        public DateTime? ISFstatusdate { get; set; }
        public string? ISFstatususer { get; set; }
        public bool denetimOK { get; set; }
        public string? denetimaciklama { get; set; }
        public bool? addtolist { get; set; }
        public string Done { get; set; } = null!;
        public string? dnPO { get; set; }
        public string? dnITR { get; set; }
        public DateTime? arsivtime { get; set; }
        public DateTime? DeliveryETA { get; set; }
        public int? deviryukno { get; set; }
        public string? FaturaAciklama { get; set; }
        public string? MasrafAciklama { get; set; }
        public int? IsfEntegrasyonStatu { get; set; }
        public bool? TransloadYuk { get; set; }
        public bool? naksekh { get; set; }
        public int? EssityIsfEntegrasyonStatu { get; set; }
        public DateTime? ISFEntegrasyonGonTarihi { get; set; }
        public string? ManuelHBL { get; set; }
        public int? tseferbaguser { get; set; }
        public string? ISFBillOnFile { get; set; }
        public DateTime? yeniETA { get; set; }
        public string? PO { get; set; }
        public int? gumrukcu { get; set; }
        public string? EmserStatus { get; set; }
        public bool? AMSIsNotBarsan { get; set; }
        public bool? ISFNotInBarsan { get; set; }
        public string? DeclarationNo { get; set; }
        public DateTime? DeclarationDate { get; set; }
        public string? TerminalWH { get; set; }
        public string? yukdepartmanyd { get; set; }
        public DateTime? FirstEta { get; set; }
    }
}
