using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Pbk.Core.Utilities.Roles
{
    public enum PagePermissions
    {
        Shipments_Create = 1,
        Shipments_Edit = 2,
        Shipments_Remove = 3,
        Stages_Create = 4,
        Stages_Edit = 5,
        Stages_Remove = 6,
        Voyages_Create = 7,
        Voyages_Edit = 8,
        Voyages_Remove = 9,
        Costs_Create = 10,
        Costs_Edit = 11,
        Costs_Remove = 12,
        Invoices_Create = 13,
        Invoices_Edit = 14,
        Invoices_Remove = 15,
        Customers_Create = 16,
        Customers_Edit = 17,
        Customers_Remove = 18,
        Vehicles_Create = 19,
        Vehicles_Edit = 20,
        Vehicles_Remove = 21,
        Reports_Create = 22,
        Reports_Download = 23,
        Departments_Edit = 24,
        Locations_Create = 25,
        Locations_Edit = 26,
        Locations_Remove = 27,
        EndPoints_Create = 28,
        EndPoints_Edit = 29,
        EndPoints_Remove = 30,
        Carriers_Create = 31,
        Carriers_Edit = 32,
        Carriers_Remove = 33,
        Users_Create = 34,
        Users_Edit = 35,
        Users_Remove = 36,
        Users_Authority = 37,
        Parameters_Create = 38,
        Parameters_Edit = 39,
        Parameters_Remove = 40,
        Drivers_Create = 41,
        Drivers_Edit = 42,
        Drivers_Remove = 43,
        Shipments_Get = 45,
        Stages_Get = 46,
        Voyages_Get = 47,
        Costs_Get = 48,
        Invoices_Get = 49,
        Customers_Get = 50,
        Vehicles_Get = 51,
        Reports_Get = 52,
        Departments_Get = 53,
        Locations_Get = 54,
        EndPoints_Get = 55,
        Carriers_Get = 56,
        Users_Get = 57,
        Parameters_Get = 58,
        Drivers_Get = 59,
        Shipments_Done = 60,
        Shipments_Planning = 61,
        Stages_Done = 63,
        Voyages_Done = 64,
    }
}
